name: My first workflow
on: push

jobs:

  analyze_job:
    name: Analyze job
    runs-on: ubuntu-latest
    steps:
      - name: Hello, world
        run: |
          echo "Hello, $WHO_TO_GREET"
        env:
          WHO_TO_GREET: ${{ secrets.NAME }}

      - name: Slack notify
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: This is my notification
          SLACK_MESSAGE: Hello from Dima
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}