name: My first workflow
on: push

jobs:
  my_first_job:
    name: Compile job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create output directory
        run: |
          mkdir out
      - name: Compile
        run: |
          script/compile.sh > out/code.compiled
      - name: Upload compiled code
        uses: actions/upload-artifact@v2
        with:
          name: compiled
          path: out/code.compiled

  my_second_job:
    name: My second job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: compiled
          path: .